GET http://localhost:3000/movies
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJzdE5hbWUiOiJ1c2VyIiwiaWF0IjoxNTU4MTEwOTQzLCJleHAiOjE1NTgxMTQ1NDN9.AxyXzhKBZkbKthx7RLHax9BMZQhQPIviBrKJmugM0wg

###

POST http://localhost:3000/movies/create
Content-Type: application/json

{
     "title": "test",
    "createdAt": "2019-04-23T10:51:59.606Z",
    "year": 1990,
    "category": "SF"
}

###

POST http://localhost:3000/register
Content-Type: application/json

{
     "email": "aaabbbb@hotmail.fr",
    "password": "izi"
}

###

DELETE http://localhost:3000/user/delete/5cc2e5c5808ebd004c1f4db1

###

PATCH http://localhost:3000/user/edit/5cc3129c20d526009142967d
Content-Type: application/json

{
     "email": "redha95@hotmail.fr",
     "firstname":"Redha"
}


###

POST http://localhost:3000/login
Content-Type: application/json

{
     "username": "user",
    "password": "password"
}